name: balldotcom
version: "1"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
  csm_service:
    build:
      context: ./csmservice
      target: development
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
  mariadb:
    container_name: mariadb
    image: mariadb
    cap_add: [SYS_NICE]
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
        - 8080:80
    depends_on:
        - "mariadb"
    cap_add: [SYS_NICE]
    environment:
        PMA_HOST: mariadb
        PMA_PASSWORD: admin
        PMA_USER: root
volumes:
    rabbitmq_data:
    rabbitmq_log:
    mariadb_data:
