name: balldotcom

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/

  eventstoredb:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - eventstore_data:/var/lib/eventstore
      - eventstore_log:/var/log/eventstore
    depends_on:
      - rabbitmq

  mariadb:
    container_name: mariadb
    image: mariadb
    cap_add: [SYS_NICE]
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
        - 8080:80
    depends_on:
        - "mariadb"
    cap_add: [SYS_NICE]
    environment:
        PMA_HOST: mariadb
        PMA_PASSWORD: admin
        PMA_USER: root

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  # Microservices
  sales_management_service:
    build:
      context: ./SalesManagement
      target: development
    ports:
      - 3000:3000
    environment:
      mongodbURL: 'mongo'
      rabbitmqURL: 'rabbitmq'
    depends_on:
      - rabbitmq

  inventory_management_service:
    build:
      context: ./InventoryManagement
      target: development
    ports:
      - 3001:3001
    environment:
      eventstoredbURL: 'eventstoredb'
      rabbitmqURL: 'rabbitmq'
    depends_on:
      - rabbitmq
      - eventstoredb

volumes:
    rabbitmq_data:
    rabbitmq_log:
    eventstore_data:
    eventstore_log:
    mariadb_data:
    mongo_data:
