[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4.3.1", features = [] }
reqwest = {version = "0.11.18", features = [] }
log = "0.4.18"
env_logger = "0.10.0"
[profile.release]
opt-level = 3

[[bin]]
name = "gateway"
path = "src/main.rs"